### ISSUE TITLE
iOS: The specified device token is invalid

### ISSUE THREAD

**Issue by Spinaker70** [Native-Push/native_push#2]
Hi!

On the iOS platform I receive a token, but for some reason it is invalid. How can I debug this in more detail?

From Apple Developer account:

![Снимок экрана от 2024-07-23 10-11-55](https://github.com/user-attachments/assets/bf13e68a-ac0e-48db-aa1d-b5c67086a4ea)

**Comment by Spinaker70** [comment]
![Снимок экрана от 2024-07-23 10-15-03](https://github.com/user-attachments/assets/e1e22c00-e762-4794-a760-371b71cce5ae)

Or will I receive a different token in production, with which there will be no problems? I'm just not very good at it yet.
In development mode, the push notification arrives normally.

**Comment by svenopdehipt** [comment]
Yes, the token will be different in production.
