### ISSUE TITLE
Android: Always the same push notification when the app is in the foreground

### ISSUE THREAD

**Issue by Spinaker70** [Native-Push/native_push#3]
--- Android ---
Found a strange bug. If I send a series of push notifications when the app is in the background, everything works fine. But if I send a series of push notifications when the app is in the foreground - I get the first push notification every time.

For each push notification I generate notification_id in data:

background1: 3bb66e88-e578-45c4-805d-827e1bcab225
background2: d2bf8df1-6a8d-432e-ae43-d177319802b3

foreground1: bd5dc742-fe2b-4adc-8044-98bec0927f38
foreground2: bd5dc742-fe2b-4adc-8044-98bec0927f38
foreground3: bd5dc742-fe2b-4adc-8044-98bec0927f38

**Comment by svenopdehipt** [comment]
I will try to look into it this weekend.

**Comment by svenopdehipt** [comment]
Should be fixed in 1.0.4

**Comment by Spinaker70** [comment]
The app crashes. Full debug log:
[log.txt](https://github.com/user-attachments/files/17107401/log.txt)

**Comment by svenopdehipt** [comment]
The solution was only working on Android 10 or above. A general solution will be live in about 10 minutes as version 1.0.5. Please let me know if this works and close the issue if it does.

**Comment by Spinaker70** [comment]
> The solution was only working on Android 10 or above

my test phone has android 9

> Please let me know if this works and close the issue if it does.

Ok

**Comment by Spinaker70** [comment]
> Please let me know if this works and close the issue if it does.

Thank you! Everything works great!

**Comment by Spinaker70** [comment]
Works.

**Comment by Spinaker70** [comment]
> Please let me know if this works and close the issue if it does.

Thank you! Everything works great!
